name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: git config core.ignorecase false
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm install
      - run: npm run build --if-present