name: Build
on: [push, pull_request_target]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      uses: actions/checkout@v4

      name: Using NPM ${{ matrix.node-version }}
      uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      run: npm run buld